In [2]:
import gym
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from matplotlib import animation
from IPython.display import display



In [5]:
env = gym.make('CartPole-v0')
observation = env.reset()

for t in range(10):
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    print(observation)

[ 0.03830346 -0.18610113 -0.04350653  0.30097919]
[ 0.03458144 -0.38057685 -0.03748694  0.57962985]
[ 0.0269699  -0.18495017 -0.02589434  0.27537741]
[ 0.0232709  -0.37969329 -0.0203868   0.55978208]
[ 0.01567703 -0.18429122 -0.00919115  0.26074657]
[ 0.01199121 -0.37928077 -0.00397622  0.55051638]
[ 0.00440559 -0.57434664  0.0070341   0.84194387]
[-0.00708134 -0.7695639   0.02387298  1.13683052]
[-0.02247262 -0.57476222  0.04660959  0.85172925]
[-0.03396786 -0.38030566  0.06364418  0.57405945]
